---
title: "Rescale Function Visualization"
output: 
  flexdashboard::flex_dashboard:
    #social: menu
    #source_code: embed
    css: my_style_rules.scss
    logo: images/HAS-logo-blauw.png
    orientation: rows
    theme: 
        version: 4
        bg: "#fff"
        fg: "#163951" 
        primary: "#163951"
        navbar-bg: "#163951"
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
if (!require(shiny)) {
  install.packages("shiny")
}
if (!require(ggplot2)) {
  install.packages("ggplot2")
}
if (!require(terra)) {
  install.packages("terra")
}
if (!require(tidyterra)) {
  install.packages("tidyterra")
}
library(shiny)
library(ggplot2)
library(tidyterra)
library(terra)

knitr::opts_chunk$set(cache = F)
```

```{r functions, include=FALSE}
# Load rescale functions
source("fuzzy_functions.r")
```

Demo {data-icon="fa-map-o"}
=====================================  

Inputs {.sidebar data-width=450}
-------------------------------------
:::{.reduce_space}
:::{.textbox}

```{r}
# shiny inputs defined here
tags$p(tags$b("Raster values"))
fluidRow(
  column(6, numericInput("range_min", "Minimum:", min = NA, max = NA, value = 0)),
  column(6, numericInput("range_max", "Maximum:", min = NA, max = NA, value = 50))
)
```
:::

```{r}
tags$div(class="textbox",tags$p(tags$b("Rescale function")),
selectInput(
  "rescale_type",
  "Select function:",
  choices = c("Linear", "Gaussian", "Power",
              "Small", "Large", "Near"),
  selected = "Linear"
),
fluidRow(
  column(6, numericInput("target_min", "Target range min:", min = NA, max = NA, value = 0)),
  column(6, numericInput("target_max", "Target range max:", min = NA, max = NA, value = 1))
),
conditionalPanel(
  condition = "input.rescale_type == 'Linear'", 
  fluidRow(
    column(6,numericInput("linear_lb", "Lower bound:", min = NA, max = NA, value = 0)),
    column(6, numericInput("linear_ub", "Upper bound:", min = NA, max = NA, value = 50))
  )
),
conditionalPanel(
  condition = "input.rescale_type == 'Power'", 
  fluidRow(
    column(6, numericInput("power_lb", "Lower bound:", min = NA, max = NA, value = 0)),
    column(6, numericInput("power_ub", "Upper bound:", min = NA, max = NA, value = 50))),
  numericInput("power_f1", "Exponent:", min = NA, max = NA, value = 2),
),
conditionalPanel(
  condition = "input.rescale_type == 'Gaussian'",
  fluidRow(
    column(6, numericInput("gaus_f2",  "Midpoint:", min = NA, max = NA, value = 25)),
    column(6, numericInput("gaus_f1","Spread:", min = NA, max = NA, value = 0.01))
  )
),
conditionalPanel(
  condition = "input.rescale_type == 'Small' || 
               input.rescale_type == 'Large'",
  fluidRow(
    column(6, numericInput("mem_f1", "Spread:", min = NA, max = NA, value = 4)),
    column(6, numericInput("mem_f2", "Midpoint:", min = NA, max = NA, value = 15))
  )
),
conditionalPanel(
  condition = "input.rescale_type == 'Near'",
  fluidRow(
    column(6, numericInput("near_f1", "Spread:", min = NA, max = NA, value = 0.06)),
    column(6, numericInput("near_f2", "Midpoint:", min = NA, max = NA, value = 25))
    )
  )
)

```

```{r}
conditionalPanel(
  condition = "input.compareplots == true",
  tags$div(class="textbox",tags$p(tags$b("Rescale function")),
  selectInput(
    "rescale_type2",
    "Selection function:",
    choices = c("Linear", "Gaussian", "Power",
                "Small", "Large", "Near"),
    selected = "Power"
  ),
  fluidRow(
    column(6, numericInput("target_min2", "target range min:", min = NA, max = NA, value = 0)),
    column(6,numericInput("target_max2", "Target range max:", min = NA, max = NA, value = 1))
  ),
  conditionalPanel(
    condition = "input.rescale_type2 == 'Linear'", 
      fluidRow(
        column(6,numericInput("linear_lb2", "Lower bound:", min = NA, max = NA, value = 0)),
        column(6, numericInput("linear_ub2", "Upper bound:", min = NA, max = NA, value = 50))
      )
    ),
    conditionalPanel(
      condition = "input.rescale_type2 == 'Power'", 
      fluidRow(
        column(6, numericInput("power_lb2", "Lower bound:", min = NA, max = NA, value = 0)),
        column(6, numericInput("power_ub2", "Upper bound:", min = NA, max = NA, value = 50))),
      numericInput("power_f12", "Exponent:", min = NA, max = NA, value = 2),
    ),
    conditionalPanel(
      condition = "input.rescale_type2 == 'Gaussian'",
      fluidRow(
        column(6, numericInput("gaus_f22",  "Midpoint:", min = NA, max = NA, value = 25)),
        column(6, numericInput("gaus_f12","Spread:", min = NA, max = NA, value = 0.01))
      )
    ),
    conditionalPanel(
      condition = "input.rescale_type2 == 'Small' || 
                         input.rescale_type2 == 'Large'",
      fluidRow(
        column(6, numericInput("mem_f12", "Spread:", min = NA, max = NA, value = 4)),
        column(6, numericInput("mem_f22", "Midpoint:", min = NA, max = NA, value = 15))
      )
    ),
    conditionalPanel(
      condition = "input.rescale_type2 == 'Near'",
      fluidRow(
        column(6, numericInput("near_f12", "Spread:", min = NA, max = NA, value = 0.06)),
        column(6, numericInput("near_f22", "Midpoint:", min = NA, max = NA, value = 25))
      )
    )
  )
)
```

```{r}
fluidRow(
  column(6, checkboxInput("compareplots", "Compare plots", FALSE)),
  column(6, checkboxInput("scale01", "Constraint y-axis to 0-1", FALSE)),
  style='height:1.8rem'
)
```

:::

Row
-------------------------------------
    
### Graph

```{r}
# Get input
range_min <- reactive(input$range_min)
range_max <- reactive(input$range_max)
target_min <- reactive(input$target_min)
target_max <- reactive(input$target_max)
rescale_type <- reactive(input$rescale_type)
linear_lb <- reactive(input$linear_lb)
linear_ub <- reactive(input$linear_ub)
gaus_f1 <- reactive(input$gaus_f1)
gaus_f2 <- reactive(input$gaus_f2)

# Generate data
x <- reactive(seq(range_min(), range_max(), length.out = 1000))


renderPlot({
  if(as.character(rescale_type()) == "Linear"){
    df <- reactive({
      data.frame(
      x = x(),
      y = linear_rescale(x(), range_min(), range_max(), linear_lb(), linear_ub(),
                        target_min(), target_max()
                        )
      )})
  } else if (as.character(rescale_type()) == "Gaussian") {
    df <- reactive({
      data.frame(
      x = x(),
      y = gaussian_rescale(x(), gaus_f1(), gaus_f2(), target_min(), target_max())
      )
    })
  }
  ggplot(df(), aes(x, y)) +
  geom_line(color="#008AFF", linewidth=1.3) +
  theme_bw(base_size = 12) +
  #ylim(tarmin, tarmax) +
  xlim(range_min(), range_max()) +
  labs(x = "Original data values", y = "Rescaled data values")
})
```
    

 
### Original layer
    
```{r}
``` 

Row
-------------------------------------
    
### Rescaled layer 1
    
```{r}
# # Create demo raster layers
# r <- s <- rast(ncol=100, nrow=100, crs="epsg:28992", extent=c(0,100, 0, 100))
# values(r) <- seq(range_min(), range_max(), length.out=100)
# values(s) <- NA
# minmaxr <- terra::minmax(r, compute=TRUE)
```
    
### Rescaled layer 2

```{r}
```

Page 2 {data-orientation=rows}
=====================================     
   
Row {data-height=600}
-------------------------------------

### Chart 1

```{r}
```

Row {data-height=400}
-------------------------------------
   
### Chart 2

```{r}
```   
    
### Chart 3

```{r}
```